// ─── Bits & Studios — Documentation Week Sprint Seeder ───────────────────────
// Run via: POST /api/admin/seed-sprint   (admin token required)
// Wipes all sub-department nodes, seeds full sprint structure.

'use strict';

const SPRINT = {
  name:     'Bits and Studios — Documentation Week',
  start:    '2026-05-24',
  end:      '2026-05-30',
  goal:     '19 documents created, reviewed, and locked across 7 owners',
  milestone:'Saturday May 30, 5pm — Sprint Review meeting',
};

const TEAM = [
  { id:'user_pratik',   name:'Pratik',   role:'admin',    color:'#534AB7', avatar:'P', department:'management' },
  { id:'user_anjalee',  name:'Anjalee',  role:'admin',    color:'#1D9E75', avatar:'A', department:'management' },
  { id:'user_sohil',    name:'Sohil',    role:'employee', color:'#D85A30', avatar:'S', department:'operations' },
  { id:'user_mohit',    name:'Mohit',    role:'employee', color:'#378ADD', avatar:'M', department:'curriculum' },
  { id:'user_aryan',    name:'Aryan',    role:'employee', color:'#D4537E', avatar:'R', department:'technology' },
  { id:'user_mantasha', name:'Mantasha', role:'employee', color:'#BA7517', avatar:'T', department:'community'  },
  { id:'user_foram',    name:'Foram',    role:'employee', color:'#639922', avatar:'F', department:'community'  },
];

// 19 documents
const DOCS = [
  // ── BRAND (5 docs) ─────────────────────────────────────────────────────────
  {
    label:      'Brand Identity Document',
    dept:       'marketing',
    area:       'Brand',
    owner:      'Pratik',   ownerId: 'user_pratik',
    support:    'Aryan',
    dueDate:    '2026-05-28',
    priority:   'critical',
    status:     'not_started',
    description:'5-7 page master document. Manifesto, mission, vision, positioning, archetype, color palette (lock final hexes), typography, visual aesthetic principles, brand enemy, voice principles.',
    icon: '💎',
    meetingDate:'2026-05-28',
  },
  {
    label:      'Brand Voice + Anti-Voice Guide',
    dept:       'marketing',
    area:       'Brand',
    owner:      'Pratik',   ownerId: 'user_pratik',
    support:    'Aryan',
    dueDate:    '2026-05-28',
    priority:   'critical',
    status:     'not_started',
    description:"10 on-brand examples, 10 off-brand examples, words we use, words we never use, tone by context, the Byju's test.",
    icon: '🗣️',
    meetingDate:'2026-05-28',
  },
  {
    label:      'Tagline + Manifesto Lock',
    dept:       'marketing',
    area:       'Brand',
    owner:      'Pratik',   ownerId: 'user_pratik',
    support:    'Team',
    dueDate:    '2026-05-27',
    priority:   'critical',
    status:     'not_started',
    description:'Final 5-line manifesto. "Build What You Imagine" tagline locked.',
    icon: '✍️',
    meetingDate:'2026-05-27',
  },
  {
    label:      'Signage + Wall Art Plan',
    dept:       'marketing',
    area:       'Brand',
    owner:      'Aryan',    ownerId: 'user_aryan',
    support:    'Mantasha',
    dueDate:    '2026-05-28',
    priority:   'critical',
    status:     'not_started',
    description:'Entry signage (brushed steel logo on navy), internal wayfinding, wall quotes (locations + content), production vendor (3 quotes), installation timeline, budget.',
    icon: '🖼️',
    meetingDate:'2026-05-28',
  },
  {
    label:      'Mountain of Making Wall Spec',
    dept:       'marketing',
    area:       'Brand',
    owner:      'Aryan',    ownerId: 'user_aryan',
    support:    'Pratik',
    dueDate:    '2026-05-28',
    priority:   'critical',
    status:     'not_started',
    description:'Feature wall — dimensions, stylized peak graphic, 4 levels labelled (Spark Forge Circuit Summit), photo mounting, lighting plan, vendor + quote. Ready by June 14.',
    icon: '🏔️',
    meetingDate:'2026-05-28',
  },
  {
    label:      'Logo Final Files',
    dept:       'marketing',
    area:       'Brand',
    owner:      'Aryan',    ownerId: 'user_aryan',
    support:    'Pratik',
    dueDate:    '2026-05-29',
    priority:   'critical',
    status:     'not_started',
    description:'Primary, stacked, icon-only, monochrome variants. PNG + SVG + AI/PDF.',
    icon: '🎨',
    meetingDate:'2026-05-29',
  },

  // ── OPERATIONS (7 docs) ────────────────────────────────────────────────────
  {
    label:      'Furniture Procurement Plan',
    dept:       'operations',
    area:       'Operations',
    owner:      'Sohil',    ownerId: 'user_sohil',
    support:    'Mantasha',
    dueDate:    '2026-05-26',
    priority:   'critical',
    status:     'not_started',
    description:'Full list across zones, 3 vendor quotes per major item, recommendations with justification, timeline, total budget, Phase 1 (office) vs Phase 2 (full space) split.',
    icon: '🪑',
    meetingDate:'2026-05-26',
  },
  {
    label:      'Lighting + Electrical Plan',
    dept:       'operations',
    area:       'Operations',
    owner:      'Sohil',    ownerId: 'user_sohil',
    support:    'Pratik',
    dueDate:    '2026-05-26',
    priority:   'critical',
    status:     'not_started',
    description:'Electrical points per zone, lighting type per zone, Edison bulb spec, UPS, 3 vendor quotes, installation timeline. Pratik approves vendor commitments.',
    icon: '💡',
    meetingDate:'2026-05-26',
  },
  {
    label:      'AC + HVAC Plan',
    dept:       'operations',
    area:       'Operations',
    owner:      'Sohil',    ownerId: 'user_sohil',
    support:    'Pratik',
    dueDate:    '2026-05-26',
    priority:   'critical',
    status:     'not_started',
    description:'Phase 1: 1 AC for 24×24 office by June 1. Phase 2: 8-9 units by June 14. Vendor quotes, installation timeline, maintenance plan.',
    icon: '❄️',
    meetingDate:'2026-05-26',
  },
  {
    label:      'Space Cleaning Plan',
    dept:       'operations',
    area:       'Operations',
    owner:      'Sohil',    ownerId: 'user_sohil',
    support:    'Foram',
    dueDate:    '2026-05-27',
    priority:   'high',
    status:     'not_started',
    description:'Deep clean schedule before fit-out, daily cleaning protocol once operational, vendor (3 quotes), materials needed.',
    icon: '🧹',
    meetingDate:'2026-05-27',
  },
  {
    label:      'Washroom Enhancement Plan',
    dept:       'operations',
    area:       'Operations',
    owner:      'Sohil',    ownerId: 'user_sohil',
    support:    'Pratik',
    dueDate:    '2026-05-27',
    priority:   'high',
    status:     'not_started',
    description:'Current state assessment, upgrades for premium parent experience, fixtures, tiles, child-friendly considerations, vendor quotes, budget.',
    icon: '🚿',
    meetingDate:'2026-05-27',
  },
  {
    label:      'Daily Operations Manual',
    dept:       'operations',
    area:       'Operations',
    owner:      'Mantasha', ownerId: 'user_mantasha',
    support:    'Foram',
    dueDate:    '2026-05-29',
    priority:   'high',
    status:     'not_started',
    description:'Morning open routine, class transitions, parent welcome script, end-of-day close routine, emergency protocols, daily checklist.',
    icon: '📋',
    meetingDate:'2026-05-29',
  },
  {
    label:      'Cleaning + Reset Protocol',
    dept:       'operations',
    area:       'Operations',
    owner:      'Foram',    ownerId: 'user_foram',
    support:    'Sohil',
    dueDate:    '2026-05-29',
    priority:   'high',
    status:     'not_started',
    description:'Daily cleaning checklist (open, transition, close), weekly deep clean, tool reset after each session, vendor specs, materials inventory.',
    icon: '♻️',
    meetingDate:'2026-05-29',
  },

  // ── PRODUCT / CURRICULUM (2 docs) ──────────────────────────────────────────
  {
    label:      'Curriculum Outlines — 4 Tracks',
    dept:       'curriculum',
    area:       'Product',
    owner:      'Mohit',    ownerId: 'user_mohit',
    support:    '',
    dueDate:    '2026-05-30',
    priority:   'critical',
    status:     'not_started',
    description:'One doc per track (Spark G1-3, Forge G4-6, Circuit G6-8, Summit G7+). Quarter-by-quarter learning arc, sample projects, materials, learning outcomes.',
    icon: '🎓',
    meetingDate:'2026-05-30',
  },
  {
    label:      'Lesson Plans — First 4 Weeks',
    dept:       'curriculum',
    area:       'Product',
    owner:      'Mohit',    ownerId: 'user_mohit',
    support:    'Mantasha + Foram',
    dueDate:    '2026-05-30',
    priority:   'critical',
    status:     'not_started',
    description:'For each track. Week 1-4 lessons. 2-hour session breakdown. Materials, learning objectives, build outcomes.',
    icon: '📚',
    meetingDate:'2026-05-30',
  },

  // ── MARKETING (5 docs) ─────────────────────────────────────────────────────
  {
    label:      'Master Contact Database',
    dept:       'marketing',
    area:       'Marketing',
    owner:      'Anjalee',  ownerId: 'user_anjalee',
    support:    'Pratik',
    dueDate:    '2026-05-27',
    priority:   'critical',
    status:     'not_started',
    description:'Google Sheet of 600+ AIS family contacts. Columns: Name, School, Phone, WhatsApp, Email, Children\'s ages, Tag (A/B/C), Last contact date, Notes, Owner, Next action.',
    icon: '📊',
    meetingDate:'2026-05-27',
  },
  {
    label:      'A/B/C Tagging Logic',
    dept:       'marketing',
    area:       'Marketing',
    owner:      'Anjalee',  ownerId: 'user_anjalee',
    support:    'Pratik',
    dueDate:    '2026-05-27',
    priority:   'critical',
    status:     'not_started',
    description:'1-pager. A-list (50 close), B-list (150 know well), C-list (400 met once). Update process, weekly review.',
    icon: '🏷️',
    meetingDate:'2026-05-27',
  },
  {
    label:      'Super-Connector Map',
    dept:       'marketing',
    area:       'Marketing',
    owner:      'Anjalee',  ownerId: 'user_anjalee',
    support:    'Pratik',
    dueDate:    '2026-05-28',
    priority:   'critical',
    status:     'not_started',
    description:'2-page doc mapping 15 most influential IB mothers. Name, school, kids\' ages, WhatsApp groups, what they value, best approach for each, Pratik\'s plan to engage personally.',
    icon: '🕸️',
    meetingDate:'2026-05-28',
  },
  {
    label:      'Testimonial Collection',
    dept:       'marketing',
    area:       'Marketing',
    owner:      'Pratik',   ownerId: 'user_pratik',
    support:    'Anjalee + Mohit',
    dueDate:    '2026-05-30',
    priority:   'critical',
    status:     'not_started',
    description:'15+ testimonials collected by May 30. 5 Ivy League/international university alumni, 5 robotics champion students, 5 current AIS parents. Mix of video, audio, written.',
    icon: '🌟',
    meetingDate:'2026-05-30',
  },
];

const MEETINGS = [
  { label:'📅 Mon May 26, 6PM — Sohil: Furniture + Lighting + AC',       dept:'operations', dueDate:'2026-05-26', assignees:['Sohil','Pratik'],          duration:'90 min', icon:'📅' },
  { label:'📅 Tue May 27, 6PM — Anjalee: DB + Tagging; Sohil: Cleaning', dept:'operations', dueDate:'2026-05-27', assignees:['Anjalee','Sohil','Pratik'], duration:'60 min', icon:'📅' },
  { label:'📅 Wed May 28, 6PM — Brand Identity + Signage + Super-Map',   dept:'marketing',  dueDate:'2026-05-28', assignees:['Pratik','Aryan','Anjalee'], duration:'90 min', icon:'📅' },
  { label:'📅 Thu May 29, 6PM — Logo + Ops Manual + Cleaning Protocol',   dept:'operations', dueDate:'2026-05-29', assignees:['Aryan','Mantasha','Foram'], duration:'60 min', icon:'📅' },
  { label:'📅 Fri May 30, 6PM — Mohit: Curriculum + Lesson Plans',       dept:'curriculum', dueDate:'2026-05-30', assignees:['Mohit','Pratik'],           duration:'90 min', icon:'📅' },
  { label:'🏁 Sat May 30, 5PM — Sprint Review (All Owners)',             dept:'management', dueDate:'2026-05-30', assignees:['Pratik','Anjalee','Sohil','Mohit','Aryan','Mantasha','Foram'], duration:'120 min', icon:'🏁' },
];

const STANDUP = {
  label:       '☀️ 9 AM Daily Standup (15 min)',
  dept:        'management',
  icon:        '☀️',
  description: 'Order: Sohil → Mohit → Aryan → Mantasha → Foram → Anjalee → Pratik\nFormat: Status only, no discussion. Mon–Sat.',
  status:      'in_progress',
  assignees:   ['Sohil','Mohit','Aryan','Mantasha','Foram','Anjalee','Pratik'],
};

module.exports = { SPRINT, TEAM, DOCS, MEETINGS, STANDUP };
